### ISSUE TITLE
ScreeningIO: Errors on startup

### ISSUE THREAD

**Issue by zah33r** [VulcanJS/Screenings#10]
### Setting up ScreeningIO

Hi guys,

I am trying to start up Screenings theme today with latest pull. 
But I am getting below error, though it was working fine till yesterday:

Any help will be appreciated.

``` sh
C:\Users\Zaheer\AppData\Local.meteor\packages\meteor-tool\1.1.8\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:278
throw(ex);
^
TypeError: Cannot read property 'func' of undefined
at Object.exception (C:\tools\utils\buildmessage.js:498:18)
at C:\tools\isobuild\compiler-plugin.js:142:26
at C:\tools\utils\buildmessage.js:356:18
at [object Object]..extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
at C:\tools\utils\buildmessage.js:349:34
at [object Object]..extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
at C:\tools\utils\buildmessage.js:347:23
at [object Object]..extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
at C:\tools\isobuild\compiler-plugin.js:129:22
at Function.time (C:\tools\tool-env\profile.js:232:28)
at C:\tools\isobuild\compiler-plugin.js:128:15
at Function..each..forEach (C:\Users\Zaheer\AppData\Local.meteor\packages\meteor-tool\1.1.8\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:87:22)
at [object Object]..extend.runCompilerPlugins (C:\tools\isobuild\compiler-plugin.js:118:7)
at ClientTarget.runCompilerPlugins (C:\tools\isobuild\bundler.js:689:22)
at C:\tools\isobuild\bundler.js:489:34
at C:\tools\utils\buildmessage.js:356:18
at [object Object]..extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
at C:\tools\utils\buildmessage.js:349:34
at [object Object]..extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
at C:\tools\utils\buildmessage.js:347:23
at [object Object]..extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
at ClientTarget.make (C:\tools\isobuild\bundler.js:483:18)
at C:\tools\isobuild\bundler.js:2062:14
at C:\tools\isobuild\bundler.js:2150:20
at Array.forEach (native)
at Function..each..forEach (C:\Users\Zaheer\AppData\Local.meteor\packages\meteor-tool\1.1.8\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
at C:\tools\isobuild\bundler.js:2149:7
at C:\tools\utils\buildmessage.js:268:13
at [object Object]..extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
at C:\tools\utils\buildmessage.js:261:29
at [object Object]..extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
at C:\tools\utils\buildmessage.js:259:18
at [object Object]..extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
at C:\tools\utils\buildmessage.js:250:23
at [object Object]..extend.withValue (C:\tools\utils\fiber-helpers.js:114:14)
at Object.capture (C:\tools\utils\buildmessage.js:249:19)
at Object.exports.bundle (C:\tools\isobuild\bundler.js:2047:31)
at C:\tools\runners\run-app.js:551:36
at time (C:\tools\tool-env\profile.js:232:28)
at Function.run (C:\tools\tool-env\profile.js:377:12)
at bundleApp (C:\tools\runners\run-app.js:541:34)
at [object Object]..extend._runOnce (C:\tools\runners\run-app.js:594:35)
at [object Object]..extend._fiber (C:\tools\runners\run-app.js:858:28)
at C:\tools\runners\run-app.js:396:12
```

**Comment by SachaG** [comment]
I should make that clearer, but Screenings is not actually a theme. I just provide the source code for educational purposes, but if you want to run it yourself then please check out Zeiss instead: https://github.com/TelescopeJS/Zeiss
